    ##spring.application.name=demo
    ##spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/postgres
    ##spring.datasource.username=${POSTGRES_USER}
    ##spring.datasource.password=${POSTGRES_PASSWORD}
    ##spring.datasource.driver-class-name=org.postgresql.Driver

    ##spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password